import { readFile, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { openUILibrary } from "../src/components/openui/openui-library";

const designRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const protocolRoot = resolve(designRoot, "../protocol/src");
const signaturesPath = resolve(protocolRoot, "openui-signatures.ts");
const schemaPath = resolve(protocolRoot, "openui-schema.generated.json");

const rawSignaturesSource = `// @generated by web/design/scripts/generate-openui-contract.ts — do not edit

import type { PromptSpec } from "@openuidev/lang-core";

export const openUIPromptSpec = ${JSON.stringify(openUILibrary.toSpec(), null, "\t")} as PromptSpec;
`;
const rawSchemaSource = `${JSON.stringify(openUILibrary.toJSONSchema(), null, "\t")}\n`;

function format(source: string, path: string): string {
	const biome = resolve(designRoot, "../../node_modules/.bin/biome");
	const result = spawnSync(biome, ["format", "--stdin-file-path", path], { input: source, encoding: "utf8" });
	if (result.status !== 0) throw new Error(result.stderr || `Biome formatting failed for ${path}`);
	return result.stdout;
}

const signaturesSource = format(rawSignaturesSource, signaturesPath);
const schemaSource = format(rawSchemaSource, schemaPath);

async function check(path: string, expected: string): Promise<boolean> {
	return (await readFile(path, "utf8").catch(() => "")) === expected;
}

if (process.argv.includes("--check")) {
	const fresh = (await check(signaturesPath, signaturesSource)) && (await check(schemaPath, schemaSource));
	if (!fresh) {
		throw new Error("OpenUI generated contract is stale. Run pnpm --filter @prime-agent/web-design generate:openui-contract");
	}
} else {
	await writeFile(signaturesPath, signaturesSource, "utf8");
	await writeFile(schemaPath, schemaSource, "utf8");
}
