organization:
    id: d0fc62ae-1f4a-4037-8ccb-d357adfdfda6
    name: Qredence
project:
    id: 31736f70-0320-4e7e-8aa6-756cfdd93058
    slug: circleci/SomxVLJYMpo86z6XUrZBUq/77Axvw4aep78EpwCW6Nsyh
    name: fleet-prime-agent
