// Schemas are defined per-domain under ./schemas. `schemas/shared` registers
// the zod-to-openapi `.openapi()` extension on the shared zod instance before
// any other fragment module is evaluated, so these re-exports are safe. The
// patched `z` helper is intentionally not re-exported (it is internal).

export {
	ProjectCreateRequestSchema,
	ProjectDirectoryBrowseResponseSchema,
	ProjectDirectoryEntrySchema,
	ProjectForkRequestSchema,
	ProjectForkResponseSchema,
	ProjectIdSchema,
	ProjectListResponseSchema,
	ProjectRenameRequestSchema,
	ProjectStatusSchema,
	ProjectSummarySchema,
} from "./fleet-contract";
export {
	ChatCommandsResponseSchema,
	ChatModelInfoSchema,
	ChatModelsDiscoverRequestSchema,
	ChatModelsDiscoverResponseSchema,
	ChatModelsResponseSchema,
	ChatProviderInfoSchema,
	ChatProviderOAuthLoginRequestSchema,
	ChatProviderOAuthLoginResponseSchema,
	ChatProviderRemoveRequestSchema,
	ChatProviderRemoveResponseSchema,
	ChatProvidersResponseSchema,
	ChatProviderUpdateRequestSchema,
	ChatProviderUpdateResponseSchema,
	ChatResourceInfoSchema,
	ChatResourcesResponseSchema,
	ChatSlashCommandInfoSchema,
	WorkspaceBrowseEntrySchema,
	WorkspaceBrowseResponseSchema,
	WorkspaceFileResponseSchema,
	WorkspaceTreeNodeSchema,
	WorkspaceTreeResponseSchema,
} from "./schemas/catalog";
export {
	ChatClarificationQuestionSchema,
	ChatCompactionEndEventSchema,
	ChatCompactionStartEventSchema,
	ChatDeltaEventSchema,
	ChatDoneEventSchema,
	ChatErrorEventSchema,
	ChatErrorPartSchema,
	ChatImagePartSchema,
	ChatMessageEventSchema,
	ChatMessagePartSchema,
	ChatMessageSchema,
	ChatModelSelectionSchema,
	ChatNewRequestSchema,
	ChatOpenUIArtifactPayloadSchema,
	ChatOpenUIArtifactUpsertRequestSchema,
	ChatOpenUIArtifactUpsertResponseSchema,
	ChatPayloadEventSchema,
	ChatPayloadPartSchema,
	ChatPendingDialogSchema,
	ChatPendingDialogsResponseSchema,
	ChatPlanEventSchema,
	ChatPlanPresentationSchema,
	ChatPlanPresentationUpsertRequestSchema,
	ChatPlanStateSchema,
	ChatPlanTodoSchema,
	ChatPresentationEventSchema,
	ChatQuestionAnswerRequestSchema,
	ChatQuestionAnswerResponseSchema,
	ChatQuestionAnswerSchema,
	ChatQueueEventSchema,
	ChatQueueMutationRequestSchema,
	ChatQueueMutationResponseSchema,
	ChatReasoningEventSchema,
	ChatReasoningPresentationSchema,
	ChatReasoningStepSchema,
	ChatRequestSchema,
	ChatRetryEndEventSchema,
	ChatRetryStartEventSchema,
	ChatRlmStreamEventSchema,
	ChatSessionInfoSchema,
	ChatSessionMetadataSchema,
	ChatSessionResponseSchema,
	ChatSessionSnapshotEventSchema,
	ChatSessionsResponseSchema,
	ChatStartEventSchema,
	ChatStateEventSchema,
	ChatStateStreamEventSchema,
	ChatStreamEventSchema,
	ChatTextPartSchema,
	ChatThinkingEventSchema,
	ChatToolEventSchema,
	ChatToolPartSchema,
	FleetAdapterCapabilitiesSchema,
	FleetAdapterFeatureSchema,
	FleetErrorCodeSchema,
	FleetErrorEnvelopeSchema,
	FleetErrorRemediationActionSchema,
	FleetErrorRemediationSchema,
	PrimeAgentArtifactRunSchema,
	PrimeAgentArtifactSchema,
	PrimeAgentGoalSchema,
	PrimeAgentParentSessionSchema,
	PrimeAgentRefinementEditSchema,
	PrimeAgentRefinementSchema,
	PrimeAgentRlmChildSchema,
	PrimeAgentRlmNodeSchema,
	PrimeAgentRlmTreeSchema,
	PrimeAgentSessionPresentationSchema,
	PrimeAgentUserBashSchema,
} from "./schemas/chat";
export { ErrorResponseSchema, HealthResponseSchema } from "./schemas/misc";
export {
	ChatPiSettingsSchema,
	ChatPiSettingsUpdateSchema,
	ChatSettingsResponseSchema,
	ChatSettingsUpdateRequestSchema,
} from "./schemas/settings";
export {
	ChatDeliveryModeSchema,
	ChatModeSchema,
	ChatPackageSourceSchema,
	ChatPlanActionSchema,
	ChatThinkingLevelSchema,
	ChatTransportSchema,
} from "./schemas/shared";
