import { BuiltinActionType, Renderer } from "@openuidev/react-lang"
import { useCallback, useMemo, useState } from "react"
import { Markdown } from "../agent-elements/markdown"

import { openUILibrary } from "./openui-library"
import { segmentOpenUIContent } from "./openui-utils"
import type {
  ActionEvent,
  OpenUIError,
  ParseResult,
} from "@openuidev/react-lang"

type OpenUIStateByBlock = Record<string, Record<string, unknown>>

function getActionMessage(event: ActionEvent) {
  if (event.type === BuiltinActionType.OpenUrl) return null

  if (event.type === BuiltinActionType.ContinueConversation) {
    const message = event.params.message
    if (typeof message === "string" && message.trim()) return message
  }

  return event.humanFriendlyMessage.trim() || null
}

function getFinalErrors(result: ParseResult | null, isStreaming?: boolean) {
  if (!result || isStreaming) return []

  const unresolvedErrors = result.meta.unresolved.map((ref) => ({
    code: "unresolved-reference",
    message: `Reference "${ref}" was used but never defined.`,
    source: "parser",
  }))

  return [...result.meta.errors, ...unresolvedErrors]
}

function OpenUIDiagnostics({
  errors,
  raw,
}: {
  errors: Array<unknown>
  raw: string
}) {
  if (errors.length === 0) return null

  const messages = errors
    .map((error) => {
      if (
        typeof error === "object" &&
        error !== null &&
        "message" in error &&
        typeof error.message === "string"
      ) {
        return error.message
      }

      return null
    })
    .filter((message): message is string => Boolean(message))

  const summary = messages[0] ?? "OpenUI output could not be rendered."

  return (
    <div className="mt-4 w-full overflow-x-auto rounded-md border border-red-500/50 bg-red-500/10 p-4 text-xs text-red-500">
      <h4 className="mb-2 font-bold">OpenUI Render Error</h4>
      <p className="mb-3 leading-relaxed">
        The generated UI could not be rendered. {summary}
      </p>
      <details className="border-t border-red-500/30 pt-3">
        <summary className="cursor-pointer font-semibold">
          Technical details
        </summary>
        <pre className="mt-3 mb-4 font-mono whitespace-pre-wrap">
          {JSON.stringify(errors, null, 2)}
        </pre>
        <div className="border-t border-red-500/30 pt-4">
          <h5 className="mb-2 font-bold">Raw output generated by AI:</h5>
          <pre className="font-mono whitespace-pre-wrap">{raw}</pre>
        </div>
      </details>
    </div>
  )
}

function OpenUIBlock({
  blockId,
  content,
  initialState,
  isStreaming,
  onAction,
  onStateUpdate,
}: {
  blockId: string
  content: string
  initialState?: Record<string, unknown>
  isStreaming?: boolean
  onAction?: (message: string) => void
  onStateUpdate: (blockId: string, state: Record<string, unknown>) => void
}) {
  const [runtimeErrors, setRuntimeErrors] = useState<Array<OpenUIError>>([])
  const [parseResult, setParseResult] = useState<ParseResult | null>(null)

  const handleError = useCallback((nextErrors: Array<OpenUIError>) => {
    if (nextErrors.length > 0) {
      console.warn("OpenUI parsing/validation errors:", nextErrors)
    }

    setTimeout(() => {
      setRuntimeErrors((previousErrors) =>
        JSON.stringify(previousErrors) === JSON.stringify(nextErrors)
          ? previousErrors
          : nextErrors
      )
    }, 0)
  }, [])

  const handleAction = useCallback(
    (event: ActionEvent) => {
      const message = getActionMessage(event)
      if (message) onAction?.(message)
    },
    [onAction]
  )

  const finalErrors = getFinalErrors(parseResult, isStreaming)

  return (
    <div className="flex w-full flex-col gap-2">
      <Renderer
        initialState={initialState}
        isStreaming={isStreaming}
        library={openUILibrary}
        response={content}
        onAction={handleAction}
        onError={handleError}
        onParseResult={setParseResult}
        onStateUpdate={(state) => onStateUpdate(blockId, state)}
      />
      <OpenUIDiagnostics
        errors={[...runtimeErrors, ...finalErrors]}
        raw={content}
      />
    </div>
  )
}

export function GenerativeTextRenderer({
  content,
  className,
  isStreaming,
  messageId,
  onOpenUIAction,
}: {
  content: string
  className?: string
  isStreaming?: boolean
  messageId?: string
  onOpenUIAction?: (message: string) => void
}) {
  const [stateByBlock, setStateByBlock] = useState<OpenUIStateByBlock>({})
  const segments = useMemo(() => segmentOpenUIContent(content), [content])

  const updateBlockState = useCallback(
    (blockId: string, state: Record<string, unknown>) => {
      setStateByBlock((previous) => ({ ...previous, [blockId]: state }))
    },
    []
  )

  if (segments.length === 1 && segments[0]?.type === "markdown") {
    return <Markdown className={className} content={content} />
  }

  return (
    <div className={`flex w-full flex-col gap-3 ${className ?? ""}`}>
      {segments.map((segment, index) => {
        if (segment.type === "markdown") {
          return (
            <Markdown
              key={`${index}-markdown`}
              content={segment.content}
              className="leading-relaxed [&_p]:leading-relaxed"
            />
          )
        }

        const blockId = `${messageId ?? "message"}:${index}`

        return (
          <OpenUIBlock
            key={blockId}
            blockId={blockId}
            content={segment.content}
            initialState={stateByBlock[blockId]}
            isStreaming={isStreaming}
            onAction={onOpenUIAction}
            onStateUpdate={updateBlockState}
          />
        )
      })}
    </div>
  )
}
